#!/bin/sh

set -e

lnk()
{
    if [ -e "$2" ]
    then
        if [ "$(readlink -e "$1")" != "$(readlink -e "$2")" ]
        then
            echo "warning: not overwriting existing file $2"
        fi
    else
        ln -s "$1" "$2"
    fi
}

mkdir -p ~/.cache/vim

lnk ~/.config/emacs/config ~/.emacs
lnk ~/.config/gnupg        ~/.gnupg
lnk ~/.config/lbdb/lbdbrc  ~/.lbdbrc
lnk ~/.config/mutt/mailcap ~/.mailcap
lnk ~/.config/mutt/muttrc  ~/.muttrc
lnk ~/.config/ssh          ~/.ssh
lnk ~/.config/vim          ~/.vim
lnk ~/.config/vim/vimrc    ~/.vimrc
lnk ~/.config/xmonad       ~/.xmonad
lnk ~/.config/zsh/zshrc    ~/.zshrc
#lnk ~/.config/xmonad/xmonad-session-rc ~/.xsession
lnk ~/.config/Xdefaults    ~/.Xdefaults

gpg2 --decrypt ~/.config/mutt/aliases.txt.gpg > ~/.mutt/aliases.txt
