#!/usr/bin/env bash

set -e

# Tag emails in muted threads that are not directly addressed to me
# with `mute`
for t in $(notmuch search --output=threads \(\(tag:mute and tag:trash\) or tag:mute\) and not to:kai.harries); do
  # Do not touch the `new` flag
  notmuch tag -inbox +mute -- tag:new and $t
done

notmuch tag -new +nixos            -- tag:new and to:nix-devel@googlegroups.com
notmuch tag -new +haskell          -- tag:new and to:haskell@haskell.org
notmuch tag -new +debian           -- tag:new and to:@lists.debian.org
notmuch tag -new +expires          -- tag:new and to:TECHNIK-SALON@listserv.uni-hannover.de
notmuch tag -new +fritzbox         -- tag:new and from:postmaster.rob@gmail.com "FRITZ!Box"
notmuch tag -new +immo             -- tag:new and from:info@mail.immowelt.de
notmuch tag -new                   -- tag:new and tag:spam

# All other mails are tagged with `p`
notmuch tag -new +inbox +unread +p -- tag:new
